FROM node:22-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY turbo.json turbo.json

COPY ./packages ./packages

COPY ./apps/http-backend ./apps/http-backend

RUN npm install


RUN npm run build

EXPOSE 8000
CMD ["npm", "run", "docker:backend"]