FROM node:22-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./packages  ./package

COPY ./apps/ws-backend ./apps/ws-backend

RUN npm install

COPY . .

RUN npm install

RUN npm run build

EXPOSE 8001

CMD [ "npm","run","start" ]